name: DevOps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verificar estructura del sitio
        run: |
          echo "Mostrando estructura del proyecto"
          ls -l
      - name: Confirmación visual
        run: echo "Página y CSS listos para despliegue."
